spring:
  application:
    name: concurrentlabs
  datasource:
    url: jdbc:postgresql://localhost:5440/concurrentlabs
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: javatestesprojects@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com
app:
  timeout-lote-segundos: 5
fake:
  requisitions:
    url: "http://localhost:8080/professor"

